version: "3.7"

services:
  api:
    build:
      context: ./docker
      dockerfile: dev.Dockerfile
    command: ["npm", "run", "dev"]
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    links:
      - db

  db:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - medprev-backend:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  medprev-backend:
