version: "3.7"

services:
  test:
    image: node:12-alpine
    user: "1000"
    command: npm run test
    environment:
      DB_TYPE: postgres
      DB_HOST: test_postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: test
      DB_DATABASE: medprev-backend-test-db
      JWT_SECRET: gKlvDwVn9kyZgRnFEAk4rTGxu0kVNwK4
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - test_postgres

  test_postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: medprev-backend-test-db
